<a href="https://colab.research.google.com/github/kikimiya0606/2024-intro-DA-code/blob/main/w03_1_3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.ndarray (shape = (2, 2), dtype = int)
a

array([[102194167629737,               0],
       [138756079114416, 138756079114864]])

In [ ]:
import numpy as np

a = np.array ([1, 2, 3], dtype = int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [ ]:
a.data

In [ ]:
import numpy as np

np.array (1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np.array (['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'], dtype=str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1, 2, 3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

In [ ]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
import numpy as np

a = np.arange (12).reshape (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.reshape(b, (2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [ ]:
print ((3-2) / (50-1))

0.02040816326530612


In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [ ]:
print((3-2)/50)

0.02


In [ ]:
np.linspace(2.0, 3.0, num = 5, retstep = True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
np.linspace(2.0, 3.0, num = 5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [ ]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [ ]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [ ]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((5,), dtype = int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [ ]:
b.shape

(2, 1)

In [ ]:
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np

np.ones((2, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye (3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
import numpy as np

np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full ([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full ([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4, 3], fill_value = np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
import numpy as np

np.empty ([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty ([2, 3], dtype = int)

array([[ 96445245387546,               0, 138590446420016],
       [             33,  96422349803488, 138590452690160]])

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.full_like (a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [ ]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [ ]:
a = np.full ((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
a @ b

array([[12,  6],
       [12,  6]])

In [ ]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [ ]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [ ]:
a = np.array ([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum()

46

In [ ]:
a.sum (axis = 0)

array([16, 30])

In [ ]:
a.sum (axis = 1)

array([30, 13,  3])

In [ ]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

46
[16 30]
[30 13  3]


In [ ]:
a = np.array ([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
a.cumsum(axis = 0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [ ]:
a.cumsum(axis = 1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [ ]:
import numpy as np

a = np.array ([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [ ]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [ ]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [ ]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [ ]:
np.add (a, b)

array([ 3,  6, 11])

In [ ]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [ ]:
np.power(a, b)

array([ 1, 16, 81])

In [4]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
print(a[3])
print(a[-2])

9
64


In [6]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [7]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [8]:
a [::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [9]:
a[::-2]

array([81, 49, 25,  9,  1])

In [10]:
a [2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [11]:
a [2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [12]:
a [2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [13]:
b = np.array ([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
b [::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [15]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [16]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [18]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [19]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [20]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [23]:
a[:,1 ]

array([ 1,  7, 13, 19, 25])

In [24]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [25]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [26]:
a[2, 4]

16

In [27]:
a[2][4]

16

In [28]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [29]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [31]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [34]:
a[:, 1, 1]

array([ 5, 17])

In [35]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [36]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [37]:
a[1, ..., 1]

array([13, 17, 21])

In [38]:
a [0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a = np.arange (12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [41]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
np.transpose(a, (0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [50]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [51]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [52]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [54]:
np.transpose (b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [56]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
c.transpose((1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [58]:
np.transpose(c, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [59]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [60]:
x = np.array ([[7, 8, 9]])
x

array([[7, 8, 9]])

In [61]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [62]:
y [0, 0] = 10
x

array([[10,  8,  9]])

In [63]:
x = np.array (np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
np.swapaxes (x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [65]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [66]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [67]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [68]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [69]:
org

array([  0,   1, 200,   3,   4])

In [70]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [71]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [72]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [73]:
org

array([0, 1, 2, 3, 4])

In [74]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [75]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
y.base

array([0, 1, 2, 3, 4, 5])

In [77]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [78]:
c = z.copy()
print(c.base)

None


In [80]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [81]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [82]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [83]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [84]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
b = a
b is a

True

In [87]:
print(id(a))
print(id(b))

135247465878640
135247465878640


In [88]:
print(b.base)

None


In [89]:
b [0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [90]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [91]:
print(id(a))
print(id(v))

135247465878640
135247465883248


In [92]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [93]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])